; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30038.1 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	?staticMetaObject@QDlgLogin@@2UQMetaObject@@B	; QDlgLogin::staticMetaObject
PUBLIC	?qt_static_metacall@QDlgLogin@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; QDlgLogin::qt_static_metacall
PUBLIC	??$staticMetaObject@$1?staticMetaObject@QDialog@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ ; QMetaObject::staticMetaObject<&QDialog::staticMetaObject>
CONST	SEGMENT
$SG138257 DB	'D:\software\qt\6.0.4\msvc2019_64\include\QtCore\qmetatyp'
	DB	'e.h', 00H
$SG138740 DB	'%s', 00H
	ORG $+1
$SG138258 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG138259 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?staticMetaObject@QDlgLogin@@2UQMetaObject@@B DQ 0000000000000000H ; QDlgLogin::staticMetaObject
	DQ	FLAT:??$staticMetaObject@$1?staticMetaObject@QDialog@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ
	DQ	FLAT:?qt_meta_stringdata_QDlgLogin@@3Uqt_meta_stringdata_QDlgLogin_t@@B
	DQ	FLAT:?qt_meta_data_QDlgLogin@@3QBIB
	DQ	FLAT:?qt_static_metacall@QDlgLogin@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
	DQ	0000000000000000H
	DQ	FLAT:??$qt_incomplete_metaTypeArray@Uqt_meta_stringdata_QDlgLogin_t@@U?$TypeAndForceComplete@XU?$integral_constant@_N$0A@@std@@@QtPrivate@@@@3QBQEBVQMetaTypeInterface@QtPrivate@@B
	DQ	0000000000000000H
?qt_meta_stringdata_QDlgLogin@@3Uqt_meta_stringdata_QDlgLogin_t@@B DD 018H ; qt_meta_stringdata_QDlgLogin
	DD	09H
	DD	022H
	DD	010H
	DD	033H
	DD	00H
	DB	051H
	DB	044H
	DB	06cH
	DB	067H
	DB	04cH
	DB	06fH
	DB	067H
	DB	069H
	DB	06eH
	DB	00H
	DB	06fH
	DB	06eH
	DB	05fH
	DB	062H
	DB	074H
	DB	06eH
	DB	04fH
	DB	06bH
	DB	05fH
	DB	063H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	00H
$SG106005 DB	'void', 00H
	ORG $+7
?qt_meta_data_QDlgLogin@@3QBIB DD 09H			; qt_meta_data_QDlgLogin
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	00H
	DD	014H
	DD	02H
	DD	08H
	DD	00H
	DD	02bH
	DD	00H
??$qt_incomplete_metaTypeArray@Uqt_meta_stringdata_QDlgLogin_t@@U?$TypeAndForceComplete@XU?$integral_constant@_N$0A@@std@@@QtPrivate@@@@3QBQEBVQMetaTypeInterface@QtPrivate@@B DQ 0000000000000000H ; qt_incomplete_metaTypeArray<qt_meta_stringdata_QDlgLogin_t,QtPrivate::TypeAndForceComplete<void,std::integral_constant<bool,0> > >
$SG138739 DB	'invalid argument', 00H
	ORG $+7
$SG138744 DB	'"', 00H, 'i', 00H, 'n', 00H, 'v', 00H, 'a', 00H, 'l', 00H
	DB	'i', 00H, 'd', 00H, ' ', 00H, 'a', 00H, 'r', 00H, 'g', 00H, 'u'
	DB	00H, 'm', 00H, 'e', 00H, 'n', 00H, 't', 00H, '"', 00H, 00H, 00H
	ORG $+2
$SG138741 DB	'D:\software\vistualStudio\vistualStudioIDE\VC\Tools\MSVC'
	DB	'\14.29.30037\include\xmemory', 00H
	ORG $+11
$SG138742 DB	'D', 00H, ':', 00H, '\', 00H, 's', 00H, 'o', 00H, 'f', 00H
	DB	't', 00H, 'w', 00H, 'a', 00H, 'r', 00H, 'e', 00H, '\', 00H, 'v'
	DB	00H, 'i', 00H, 's', 00H, 't', 00H, 'u', 00H, 'a', 00H, 'l', 00H
	DB	'S', 00H, 't', 00H, 'u', 00H, 'd', 00H, 'i', 00H, 'o', 00H, '\'
	DB	00H, 'v', 00H, 'i', 00H, 's', 00H, 't', 00H, 'u', 00H, 'a', 00H
	DB	'l', 00H, 'S', 00H, 't', 00H, 'u', 00H, 'd', 00H, 'i', 00H, 'o'
	DB	00H, 'I', 00H, 'D', 00H, 'E', 00H, '\', 00H, 'V', 00H, 'C', 00H
	DB	'\', 00H, 'T', 00H, 'o', 00H, 'o', 00H, 'l', 00H, 's', 00H, '\'
	DB	00H, 'M', 00H, 'S', 00H, 'V', 00H, 'C', 00H, '\', 00H, '1', 00H
	DB	'4', 00H, '.', 00H, '2', 00H, '9', 00H, '.', 00H, '3', 00H, '0'
	DB	00H, '0', 00H, '3', 00H, '7', 00H, '\', 00H, 'i', 00H, 'n', 00H
	DB	'c', 00H, 'l', 00H, 'u', 00H, 'd', 00H, 'e', 00H, '\', 00H, 'x'
	DB	00H, 'm', 00H, 'e', 00H, 'm', 00H, 'o', 00H, 'r', 00H, 'y', 00H
	DB	00H, 00H
	ORG $+6
$SG138743 DB	's', 00H, 't', 00H, 'd', 00H, ':', 00H, ':', 00H, '_', 00H
	DB	'A', 00H, 'l', 00H, 'l', 00H, 'o', 00H, 'c', 00H, 'a', 00H, 't'
	DB	00H, 'e', 00H, '_', 00H, 'm', 00H, 'a', 00H, 'n', 00H, 'u', 00H
	DB	'a', 00H, 'l', 00H, 'l', 00H, 'y', 00H, '_', 00H, 'v', 00H, 'e'
	DB	00H, 'c', 00H, 't', 00H, 'o', 00H, 'r', 00H, '_', 00H, 'a', 00H
	DB	'l', 00H, 'i', 00H, 'g', 00H, 'n', 00H, 'e', 00H, 'd', 00H, 00H
	DB	00H
CONST	ENDS
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@QDlgLogin@@UEBAPEBUQMetaObject@@XZ	; QDlgLogin::metaObject
PUBLIC	?qt_metacast@QDlgLogin@@UEAAPEAXPEBD@Z		; QDlgLogin::qt_metacast
PUBLIC	?qt_metacall@QDlgLogin@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; QDlgLogin::qt_metacall
EXTRN	strcmp:PROC
EXTRN	__imp_??0QMetaType@@QEAA@XZ:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QDialog@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QDialog@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?on_btnOk_clicked@QDlgLogin@@AEAAXXZ:PROC	; QDlgLogin::on_btnOk_clicked
EXTRN	__imp_?staticMetaObject@QDialog@@2UQMetaObject@@B:ZWORD
pdata	SEGMENT
$pdata$?metaObject@QDlgLogin@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@QDlgLogin@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@QDlgLogin@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@QDlgLogin@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@QDlgLogin@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+205
	DD	imagerel $unwind$?qt_metacall@QDlgLogin@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@QDlgLogin@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN8
	DD	imagerel $LN8+72
	DD	imagerel $unwind$?qt_static_metacall@QDlgLogin@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
xdata	SEGMENT
$unwind$?metaObject@QDlgLogin@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@QDlgLogin@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@QDlgLogin@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 021801H
	DD	070145218H
$unwind$?qt_static_metacall@QDlgLogin@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	06217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??$staticMetaObject@$1?staticMetaObject@QDialog@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ
_TEXT	SEGMENT
??$staticMetaObject@$1?staticMetaObject@QDialog@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ PROC ; QMetaObject::staticMetaObject<&QDialog::staticMetaObject>, COMDAT
; File D:\software\qt\6.0.4\msvc2019_64\include\QtCore\qobjectdefs.h
; Line 398
	mov	rax, QWORD PTR __imp_?staticMetaObject@QDialog@@2UQMetaObject@@B
; Line 399
	ret	0
??$staticMetaObject@$1?staticMetaObject@QDialog@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ ENDP ; QMetaObject::staticMetaObject<&QDialog::staticMetaObject>
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
_o$ = 64
_c$ = 72
_id$ = 80
_a$ = 88
?qt_static_metacall@QDlgLogin@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; QDlgLogin::qt_static_metacall
; File C:\Users\lwq\Documents\GitHub\WeClound\debug\moc\moc_qdlglogin.cpp
; Line 64
$LN8:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 65
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN4@qt_static_
; Line 66
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 68
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 0
	je	SHORT $LN5@qt_static_
	jmp	SHORT $LN6@qt_static_
$LN5@qt_static_:
; Line 69
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?on_btnOk_clicked@QDlgLogin@@AEAAXXZ	; QDlgLogin::on_btnOk_clicked
$LN6@qt_static_:
$LN4@qt_static_:
; Line 74
	add	rsp, 56					; 00000038H
	ret	0
?qt_static_metacall@QDlgLogin@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; QDlgLogin::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
$T1 = 32
this$ = 64
_c$ = 72
_id$ = 80
_a$ = 88
?qt_metacall@QDlgLogin@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; QDlgLogin::qt_metacall
; File C:\Users\lwq\Documents\GitHub\WeClound\debug\moc\moc_qdlglogin.cpp
; Line 106
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	push	rdi
	sub	rsp, 48					; 00000030H
; Line 107
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QDialog@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 108
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 109
	mov	eax, DWORD PTR _id$[rsp]
	jmp	$LN1@qt_metacal
$LN2@qt_metacal:
; Line 110
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 111
	cmp	DWORD PTR _id$[rsp], 1
	jge	SHORT $LN5@qt_metacal
; Line 112
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@QDlgLogin@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; QDlgLogin::qt_static_metacall
$LN5@qt_metacal:
; Line 113
	mov	eax, DWORD PTR _id$[rsp]
	dec	eax
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 114
	cmp	DWORD PTR _c$[rsp], 7
	jne	SHORT $LN6@qt_metacal
; Line 115
	cmp	DWORD PTR _id$[rsp], 1
	jge	SHORT $LN7@qt_metacal
; Line 116
	lea	rax, QWORD PTR $T1[rsp]
	mov	rdi, rax
	xor	eax, eax
	mov	ecx, 8
	rep stosb
	lea	rcx, QWORD PTR $T1[rsp]
	call	QWORD PTR __imp_??0QMetaType@@QEAA@XZ
	mov	rax, QWORD PTR [rax]
	mov	ecx, 8
	imul	rcx, rcx, 0
	mov	rdx, QWORD PTR _a$[rsp]
	mov	rcx, QWORD PTR [rdx+rcx]
	mov	QWORD PTR [rcx], rax
$LN7@qt_metacal:
; Line 117
	mov	eax, DWORD PTR _id$[rsp]
	dec	eax
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 119
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 120
	add	rsp, 48					; 00000030H
	pop	rdi
	ret	0
?qt_metacall@QDlgLogin@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; QDlgLogin::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@QDlgLogin@@UEAAPEAXPEBD@Z PROC		; QDlgLogin::qt_metacast
; File C:\Users\lwq\Documents\GitHub\WeClound\debug\moc\moc_qdlglogin.cpp
; Line 98
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 99
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 100
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_QDlgLogin@@3Uqt_meta_stringdata_QDlgLogin_t@@B+24
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 101
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 102
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QDialog@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 103
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@QDlgLogin@@UEAAPEAXPEBD@Z ENDP		; QDlgLogin::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@QDlgLogin@@UEBAPEBUQMetaObject@@XZ PROC	; QDlgLogin::metaObject
; File C:\Users\lwq\Documents\GitHub\WeClound\debug\moc\moc_qdlglogin.cpp
; Line 93
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 94
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+56], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@QDlgLogin@@2UQMetaObject@@B ; QDlgLogin::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 95
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@QDlgLogin@@UEBAPEBUQMetaObject@@XZ ENDP	; QDlgLogin::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File D:\software\qt\6.0.4\msvc2019_64\include\QtCore\qscopedpointer.h
; Line 116
	mov	QWORD PTR [rsp+8], rcx
; Line 117
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 118
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
END
